### ISSUE TITLE
Load MLIntentMatcher models that are not in classpath

### ISSUE THREAD

**Issue by wiseman** [rabidgremlin/Mutters#1]
Hi! I love this library--I've had good success creating chatbots with Microsoft LUIS for intent matching & entity extraction, and Ink for state/sequencing, so I think it's a great idea.

What do you think about adding the ability to load intent models that aren't in the classpath/aren't resources?  Maybe add an `MLIntentMatcher` constructor that takes a `URL` for the model, so it can load from anywhere?

**Comment by rabidgremlin** [comment]
Should be doable.

**Comment by rabidgremlin** [comment]
Have pushed com.rabidgremlin:mutters:1.1.0-SNAPSHOT to sonatype repo. Give it a whirl and let me know if the change works for you.

**Comment by rabidgremlin** [comment]
Change now in new release.

**Comment by wiseman** [comment]
Looks good, thanks!
