### ISSUE TITLE
Upgrade to ink 0.9.0

### ISSUE THREAD

**Issue by wilmol** [rabidgremlin/Mutters#24]
- Upgrade to latest ink version (0.9.0) by upgrading to latest blade ink (0.7.0)

**Comment by wilmol** [comment]
working on this

will upgrade to Blade Ink v0.7.1

**Comment by rabidgremlin** [comment]
Need an Ink bug: https://github.com/inkle/ink/issues/556 to be resolved to avoid breaking an existing Ink based production bot :)

**Comment by wilmol** [comment]
@rabidgremlin confirmed that blade-ink 0.7.3 resolves the issue, so can unblock.

maybe tell inkle guys it wasn't on their end?

**Comment by rabidgremlin** [comment]
Will be upgraded in v7.0.0 release.
