### ISSUE TITLE
Add code linter, CI tool and fix code warnings

### ISSUE THREAD

**Issue by wilmol** [rabidgremlin/Mutters#25]
- Add code linter (checkstyle + spotless) to apply consistent code formatting (for Java)
- Fix code warnings by running code analysis tool (e.g. IntelliJ)
- EXTRA: setup CI tool (e.g. travis/circle/github actions) to run build against PRs

**Comment by wilmol** [comment]
should wait for all PRs to be merged before starting this

**Comment by rabidgremlin** [comment]
Have added this to v6 branch.

**Comment by wilmol** [comment]
#31 resolved this
